# Generated by Django 3.1.7 on 2021-03-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
